//! Workspace identifiers.
//!
//! Each workspace has a unique ID derived from the original path where it was
//! initialized. This allows the workspace to be identified even if moved.

use std::{fmt, path::Path, str::FromStr};

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// A unique identifier for a workspace.
///
/// Generated by hashing the canonical path at initialization time.
/// The ID is stable even if the project symlink is moved.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WorkspaceId([u8; 16]);

impl WorkspaceId {
    /// Create a new workspace ID from the given path.
    ///
    /// The path is canonicalized and hashed to produce a stable ID.
    #[must_use]
    pub fn from_path(path: &Path) -> Self {
        let canonical = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
        let path_str = canonical.to_string_lossy();
        let hash = blake3::hash(path_str.as_bytes());
        let mut id = [0u8; 16];
        id.copy_from_slice(&hash.as_bytes()[..16]);
        Self(id)
    }

    /// Create a workspace ID from raw bytes.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Get the raw bytes of this ID.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }

    /// Get a short hex representation suitable for directory names.
    #[must_use]
    pub fn to_hex(&self) -> String {
        hex::encode(self.0)
    }
}

impl fmt::Display for WorkspaceId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_hex())
    }
}

impl FromStr for WorkspaceId {
    type Err = ParseWorkspaceIdError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let bytes = hex::decode(s).map_err(|_| ParseWorkspaceIdError::InvalidHex)?;
        if bytes.len() != 16 {
            return Err(ParseWorkspaceIdError::InvalidLength {
                expected: 16,
                actual: bytes.len(),
            });
        }
        let mut id = [0u8; 16];
        id.copy_from_slice(&bytes);
        Ok(Self(id))
    }
}

/// Error parsing a workspace ID from a string.
#[derive(Debug, Clone, Copy, Error)]
pub enum ParseWorkspaceIdError {
    /// Invalid hex encoding.
    #[error("invalid hex encoding")]
    InvalidHex,

    /// Wrong number of bytes.
    #[error("expected {expected} bytes, got {actual}")]
    InvalidLength {
        /// Expected byte count.
        expected: usize,
        /// Actual byte count.
        actual: usize,
    },
}

#[allow(clippy::panic)]
#[cfg(test)]
mod tests {
    use super::*;
    use bolero::check;

    #[test]
    fn from_path_is_deterministic() {
        check!().with_type::<String>().for_each(|s: &String| {
            let path = Path::new(s);
            let id1 = WorkspaceId::from_path(path);
            let id2 = WorkspaceId::from_path(path);
            assert_eq!(id1, id2, "same path should produce same id");
        });
    }

    #[allow(clippy::expect_used)]
    #[test]
    fn hex_roundtrip() {
        check!()
            .with_type::<[u8; 16]>()
            .for_each(|bytes: &[u8; 16]| {
                let id = WorkspaceId::from_bytes(*bytes);
                let hex = id.to_hex();
                let parsed: WorkspaceId = hex.parse().expect("parse hex");
                assert_eq!(id, parsed);
            });
    }

    #[test]
    fn display_shows_hex() {
        let id = WorkspaceId::from_bytes([
            0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54,
            0x32, 0x10,
        ]);
        assert_eq!(id.to_string(), "0123456789abcdeffedcba9876543210");
    }
}
